# Generated by Django 3.2.9 on 2021-11-20 16:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[api.models.validates_cnpj])),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[api.models.validates_cpf])),
                ('companies', models.ManyToManyField(blank=True, to='api.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, to='api.Employee'),
        ),
    ]
